data:
  colormode: RGB
  inference:
    normalize_images: true
    resize:
      height: 640
      width: 480
      keep_ratio: true
  train:
    affine:
      p: 0.5
      rotation: 30
      scaling:
      - 0.7
      - 1.25
      translation: 25
    collate:
      type: ResizeFromDataSizeCollate
      min_scale: 0.4
      max_scale: 1.0
      min_short_side: 128
      max_short_side: 1280
      multiple_of: 32
      to_square: false
    resize:
      height: 640
      width: 480
      keep_ratio: true
    covering: true
    gaussian_noise: 12.75
    hist_eq: false
    motion_blur: false
    normalize_images: true
    hflip: false
device: auto
metadata:
  project_path: 
    /project/nicho/projects/marmosets/dlc_project_files/full_marmoset_model-Dalton-2024-10-27
  pose_config_path: 
    /project/nicho/projects/marmosets/dlc_project_files/full_marmoset_model-Dalton-2024-10-27/dlc-models-pytorch/iteration-0/full_marmoset_model_Oct27-trainset95shuffle1/train/pose_cfg.yaml
  bodyparts:
  - r-head-front
  - r-head-corner
  - r-head-under-tab
  - r-shoulder
  - r-elbow
  - r-wrist
  - r-d5-mcp
  - r-d5-dip
  - r-d2-mcp
  - r-d2-dip
  - l-head-front
  - l-head-corner
  - l-head-under-tab
  - l-shoulder
  - l-elbow
  - l-wrist
  - l-d5-mcp
  - l-d5-dip
  - l-d2-mcp
  - l-d2-dip
  - origin
  - x
  - y
  - partition_top_right
  - partition_top_left

  unique_bodyparts: []
  individuals:
  - animal
  with_identity:
method: bu
model:
  backbone:
    type: ResNet
    model_name: resnet50_gn
    output_stride: 16
    freeze_bn_stats: true
    freeze_bn_weights: false
  backbone_output_channels: 2048
  heads:
    bodypart:
      type: HeatmapHead
      weight_init: normal
      predictor:
        type: HeatmapPredictor
        apply_sigmoid: false
        clip_scores: true
        location_refinement: true
        locref_std: 7.2801
      target_generator:
        type: HeatmapGaussianGenerator
        num_heatmaps: 25
        pos_dist_thresh: 17
        heatmap_mode: KEYPOINT
        generate_locref: true
        locref_std: 7.2801
      criterion:
        heatmap:
          type: WeightedMSECriterion
          weight: 1.0
        locref:
          type: WeightedHuberCriterion
          weight: 0.05
      heatmap_config:
        channels:
        - 2048
        - 25
        kernel_size:
        - 3
        strides:
        - 2
      locref_config:
        channels:
        - 2048
        - 50
        kernel_size:
        - 3
        strides:
        - 2
net_type: resnet_50
runner:
  type: PoseTrainingRunner
  gpus:
  key_metric: test.mAP
  key_metric_asc: true
  eval_interval: 1
  optimizer:
    type: AdamW
    params:
      lr: 0.0001
  scheduler:
    type: LRListScheduler
    params:
      lr_list:
      - - 1e-05
      - - 1e-06
      milestones:
      - 160
      - 190
  snapshots:
    max_snapshots: 10
    save_epochs: 25
    save_optimizer_state: false
train_settings:
  batch_size: 16
  dataloader_workers: 0
  dataloader_pin_memory: true
  display_iters: 1000
  epochs: 200
  seed: 42
